// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateContact(arg1) {
  return window['go']['main']['App']['CreateContact'](arg1);
}

export function CreateSMSTemplate(arg1) {
  return window['go']['main']['App']['CreateSMSTemplate'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteSMSTemplate(arg1) {
  return window['go']['main']['App']['DeleteSMSTemplate'](arg1);
}

export function ExportVCF() {
  return window['go']['main']['App']['ExportVCF']();
}

export function GetOdorikBalance() {
  return window['go']['main']['App']['GetOdorikBalance']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVoicemailAudioDataURL(arg1) {
  return window['go']['main']['App']['GetVoicemailAudioDataURL'](arg1);
}

export function ImportVCF(arg1) {
  return window['go']['main']['App']['ImportVCF'](arg1);
}

export function ListContacts() {
  return window['go']['main']['App']['ListContacts']();
}

export function ListSMSMessages(arg1) {
  return window['go']['main']['App']['ListSMSMessages'](arg1);
}

export function ListSMSTemplates() {
  return window['go']['main']['App']['ListSMSTemplates']();
}

export function ListVoicemails(arg1) {
  return window['go']['main']['App']['ListVoicemails'](arg1);
}

export function PatchSettings(arg1) {
  return window['go']['main']['App']['PatchSettings'](arg1);
}

export function SendSMS(arg1) {
  return window['go']['main']['App']['SendSMS'](arg1);
}

export function SetSMSMessageChecked(arg1, arg2) {
  return window['go']['main']['App']['SetSMSMessageChecked'](arg1, arg2);
}

export function SetVoicemailChecked(arg1, arg2) {
  return window['go']['main']['App']['SetVoicemailChecked'](arg1, arg2);
}

export function SyncVoicemails(arg1) {
  return window['go']['main']['App']['SyncVoicemails'](arg1);
}

export function UpdateContact(arg1) {
  return window['go']['main']['App']['UpdateContact'](arg1);
}

export function UpdateSMSTemplate(arg1) {
  return window['go']['main']['App']['UpdateSMSTemplate'](arg1);
}
