// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CreateContact(arg1:core.CreateContactRequest):Promise<core.ContactInfo>;

export function CreateSMSTemplate(arg1:core.CreateSMSTemplateRequest):Promise<core.SMSTemplate>;

export function DeleteContact(arg1:number):Promise<core.DeleteContactResponse>;

export function DeleteSMSTemplate(arg1:number):Promise<core.DeleteSMSTemplateResponse>;

export function ExportVCF():Promise<core.ExportVCFResponse>;

export function GetOdorikBalance():Promise<core.OdorikBalanceResponse>;

export function GetSettings():Promise<core.SettingsResponse>;

export function GetVoicemailAudioDataURL(arg1:number):Promise<string>;

export function ImportVCF(arg1:core.ImportVCFRequest):Promise<core.ImportVCFResponse>;

export function ListContacts():Promise<Array<core.ContactInfo>>;

export function ListSMSHistory(arg1:core.ListSMSHistoryRequest):Promise<core.ListSMSHistoryResponse>;

export function ListSMSMessages(arg1:core.ListSMSMessagesRequest):Promise<core.ListSMSMessagesResponse>;

export function ListSMSTemplates():Promise<Array<core.SMSTemplate>>;

export function ListVoicemails(arg1:core.ListVoicemailsRequest):Promise<core.ListVoicemailsResponse>;

export function PatchSettings(arg1:core.PatchSettingsRequest):Promise<core.PatchSettingsResponse>;

export function SendSMS(arg1:core.SendSMSRequest):Promise<core.SendSMSResponse>;

export function SetSMSMessageChecked(arg1:number,arg2:boolean):Promise<core.UpdateCheckedResponse>;

export function SetVoicemailChecked(arg1:number,arg2:boolean):Promise<core.UpdateCheckedResponse>;

export function SyncVoicemails(arg1:number):Promise<core.SyncResponse>;

export function UpdateContact(arg1:core.UpdateContactRequest):Promise<core.ContactInfo>;

export function UpdateSMSTemplate(arg1:core.UpdateSMSTemplateRequest):Promise<core.SMSTemplate>;
